version: "3.4"

services:
  node:
    build:
      context: ..
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    ports:
      - "8000:8000"
    volumes:
      - app:/srv/app
volumes:
  app:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ".."